document.addEventListener("DOMContentLoaded",(()=>{const t=document.querySelector(".song-name");new MutationObserver((e=>{for(const n of e)if("childList"===n.type){const e=t.textContent.trim();document.title=`${e} - VL Beats`}})).observe(t,{childList:!0,subtree:!1})}));

document.addEventListener("DOMContentLoaded",(function(){document.getElementById("full-screen-mode").addEventListener("click",(function(){document.getElementById("music-player").requestFullscreen().then((()=>{document.querySelectorAll("#full-screen-mode, #resize-mode, .queue-button, .song-info-pop").forEach((e=>{e.classList.add("hidden")})),document.getElementById("full-screen-exit-mode").classList.remove("hidden")}))})),document.getElementById("full-screen-exit-mode").addEventListener("click",(function(){document.fullscreenElement&&document.exitFullscreen().then((()=>{document.querySelectorAll("#full-screen-mode, #resize-mode, .queue-button, .song-info-pop").forEach((e=>{e.classList.remove("hidden")})),document.getElementById("full-screen-exit-mode").classList.add("hidden")}))})),document.addEventListener("fullscreenchange",(function(){document.fullscreenElement||(document.querySelectorAll("#full-screen-mode, #resize-mode, .queue-button, .song-info-pop").forEach((e=>{e.classList.remove("hidden")})),document.getElementById("full-screen-exit-mode").classList.add("hidden"))}))}));

document.addEventListener("DOMContentLoaded",(function(){const t=document.querySelector(".seek-slider-top"),e=document.getElementById("timerRight");const n=document.createElement("div");n.className="tooltip",t.appendChild(n),t.addEventListener("mousemove",(function(o){const i=t.offsetWidth,d=t.getBoundingClientRect(),s=o.clientX-d.left,a=s/i,c=function(t){const[e,n]=t.split(":").map(Number);return 60*e+n}(e.textContent),r=function(t){const e=Math.floor(t/60);return t=Math.floor(t%60),`${String(e).padStart(2,"0")}:${String(t).padStart(2,"0")}`}(Math.round(a*c));n.textContent=r;const l=n.offsetWidth,u=Math.min(Math.max(s-l/2,0),i-l);n.style.left=`${u}px`,n.style.top=`-${n.offsetHeight+10}px`,n.style.opacity="1"})),t.addEventListener("mouseleave",(function(){n.style.opacity="0"}))}));

document.addEventListener("DOMContentLoaded",(function(){function t(t){let e=function(){const t=localStorage.getItem("isRecentSongs");return t?JSON.parse(t):[]}();e=e.filter((e=>e!==t)),e.unshift(t),e.length>9&&(e=e.slice(0,9)),localStorage.setItem("isRecentSongs",JSON.stringify(e))}function e(){const e=localStorage.getItem("musicFromPost");e&&t(e)}const n=document.getElementById("play-song-post"),o=document.getElementById("play-btn");n&&n.addEventListener("click",e),o&&o.addEventListener("click",e)}));

document.addEventListener("DOMContentLoaded",(function(){const e=document.getElementById("music-player"),t=document.getElementById("resize-mode"),n=document.getElementById("open-player-mode"),d=document.body;function c(){e.classList.contains("playerShow")||(e.classList.add("playerShow"),d.classList.add("iPlayerS"))}e.addEventListener("click",(function(t){t.target===e&&c()})),n.addEventListener("click",c),t.addEventListener("click",(function(){e.classList.remove("playerShow"),d.classList.remove("iPlayerS")}))}));

function updateMusicPlayerBackground(){const e=document.getElementById("music-player"),t=document.getElementById("album-art"),a=window.getComputedStyle(t).backgroundImage.match(/url\("?(.*?)"?\)/);if(a){const t=a[1];e.classList.contains("playerShow")?e.style.backgroundImage=`linear-gradient(rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0.65) 30%, rgba(0, 0, 0, 0.8) 55%, black 85%, black 100%), url(${t})`:e.style.backgroundImage=""}}function monitorChanges(){new MutationObserver((()=>{updateMusicPlayerBackground()})).observe(document.getElementById("album-art"),{attributes:!0,attributeFilter:["style"]}),setInterval(updateMusicPlayerBackground,100)}document.addEventListener("DOMContentLoaded",monitorChanges);

document.addEventListener("DOMContentLoaded",(()=>{function e(){const e=document.getElementById("timer").innerText,[t,n]=e.split(" / ");document.getElementById("timerLeft").innerText=t,document.getElementById("timerRight").innerText=n}const t=document.getElementById("timer");new MutationObserver(e).observe(t,{characterData:!0,childList:!0,subtree:!0}),e()}));
