function addStyleModified(){/Mobi|Android|iPhone|iPad|iPod|Windows Phone|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)&&setTimeout(()=>{let e=document.getElementById("HTML01");e&&(e.style.overflow="visible")},3e3)}addStyleModified();

function transLanguage(){const t=document.querySelector(".lyricsContainer[data-translated]"),a=document.querySelector(".lrTrans");if(t&&a){a.classList.remove("hidden");const e=t.getAttribute("data-translated"),i=a.querySelector("#lrTrns");if(e&&i){i.setAttribute("data-text","View in");const t={Telugu:"తెలుగు",Tamil:"தமிழ்",Bangla:"বাংলা",Korean:"한국인",Hindi:"हिंदी",Nepali:"नेपाली",Odia:"ଓଡ଼ିଆ",Kannada:"ಕನ್ನಡ",Malayalam:"മലയാളം",English:"English"}[e]||"Native";i.innerHTML=t}a.hasAttribute("data-event-attached")||(a.addEventListener("click",function(){if(a.classList.contains("is-active"))a.classList.remove("is-active"),t.classList.remove("translated"),t.querySelectorAll("span.iTranslatedL").forEach(t=>{const a=t.getAttribute("data-hidden-lyrics");a&&(t.innerHTML=a,t.removeAttribute("data-hidden-lyrics"),t.classList.remove("iTranslatedL"))});else{a.classList.add("is-active"),t.classList.add("translated"),t.querySelectorAll("span:not([data-text])").forEach(t=>{"<br>"!==t.innerHTML.trim()&&"<br/>"!==t.innerHTML.trim()&&(t.classList.contains("iTranslatedL")||(t.setAttribute("data-hidden-lyrics",t.innerHTML.trim()),t.innerHTML="",t.classList.add("iTranslatedL")))})}}),a.setAttribute("data-event-attached","true"))}}transLanguage();

function updateContributorText(){const t=document.querySelector(".aboutSongVL"),e=document.querySelector(".lyricsContainer")||document.querySelector(".lyricsContain"),o=document.getElementById("contributor");if(!o)return void console.error("Contributor element not found!");const r=t&&t.textContent.includes("Odia");if(e&&e.hasAttribute("data-contributor")){const t=e.getAttribute("data-contributor");o.setAttribute("data-text",t)}else r?o.setAttribute("data-text","Amit Kumar Sahoo"):o.setAttribute("data-text","Admin")}updateContributorText();

function handleSyncLyrics(){document.querySelectorAll(".lyricsContainer, .lyricsContain").forEach(e=>{if("true"===e.getAttribute("data-sync-lyrics")){const e=document.querySelector(".addR.sn");e&&(e.innerHTML="",e.innerHTML='<svg viewBox="0 0 24 24"><path d="M18.686,6.025c-0.357,0.015-0.702,0.134-0.96,0.39L9.023,15.09l-2.674-2.645c-0.528-0.523-1.387-0.521-1.916,0 c-0.261,0.258-0.405,0.603-0.404,0.969c0,0.367,0.144,0.711,0.404,0.969l3.625,3.584c0.279,0.277,0.604,0.417,0.966,0.417 c0.362,0,0.687-0.14,0.966-0.417l9.625-9.662c0.517-0.517,0.525-1.337,0.021-1.867C19.386,6.176,19.048,6.029,18.686,6.025z"></path></svg>',e.classList.add("vF"));const t=document.querySelector(".addN.sync .addL");t&&t.classList.add("vF");const c=document.querySelector(".iN.bS.b");c&&c.setAttribute("data-text","Verified by VergeLyrics")}else{const e=document.querySelector(".addR.sn");if(e){e.innerHTML="",e.innerHTML='<svg viewBox="0 0 24 24"><path d="M5.3,18.7C5.5,18.9,5.7,19,6,19s0.5-0.1,0.7-0.3l5.3-5.3l5.3,5.3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3 c0.4-0.4,0.4-1,0-1.4L13.4,12l5.3-5.3c0.4-0.4,0.4-1,0-1.4s-1-0.4-1.4,0L12,10.6L6.7,5.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4 l5.3,5.3l-5.3,5.3C4.9,17.7,4.9,18.3,5.3,18.7z"></path></svg>';const t=document.querySelector(".iN.bS.b");t&&t.setAttribute("data-text","Not synced")}}})}handleSyncLyrics();

function initializeAudioControls(e){const t=document.querySelector(e.audio),i=document.querySelector(e.audioOn),o=document.querySelector(e.audioMute);if(!t||!i||!o)return void console.error("Required elements not found in the DOM.");const n=()=>{localStorage.getItem("AudioMuted")?t.classList.add("is-active"):t.classList.remove("is-active")};n(),i.addEventListener("click",()=>{localStorage.setItem("AudioMuted","true"),n()}),o.addEventListener("click",()=>{localStorage.removeItem("AudioMuted"),n()}),new MutationObserver(()=>{n()}).observe(document.body,{childList:!0,subtree:!0}),window.addEventListener("storage",e=>{"AudioMuted"===e.key&&n()})}function waitForElementsAndInitialize(e){const t=document.querySelector(e.audio),i=document.querySelector(e.audioOn),o=document.querySelector(e.audioMute);t&&i&&o?initializeAudioControls(e):setTimeout(()=>waitForElementsAndInitialize(e),100)}waitForElementsAndInitialize({audio:".iAudio",audioOn:".iAOn",audioMute:".iAMute"});
